# set base image
ARG IMAGE_BASE=base
FROM feedsbrain/buildmystack:${IMAGE_BASE}

# disable prompt
ENV DEBIAN_FRONTEND noninteractive

# copy build script
ARG TOOLS=base
COPY build_scripts/build-${TOOLS}.sh build.sh
RUN sudo chmod +x build.sh

# run build & clean script
RUN ./build.sh && rm build.sh
