name: Publish Docker image

on:
  release:
    branches:
      - "master"
    types:
      - "published"
    tags:
      - "v*"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: feedsbrain/buildmystack
          tags: |
            # minimal
            type=semver,pattern={{version}}
            # use custom value instead of git tag
            type=semver,pattern={{version}},value=v1.0.0

      - name: Build and push Docker base image
        run: |
          VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}

          docker build -f Dockerfile -t feedsbrain/buildmystack:latest .
          docker tag feedsbrain/buildmystack:latest feedsbrain/buildmystack:$VERSION
          docker push feedsbrain/buildmystack:latest
          docker push feedsbrain/buildmystack:$VERSION
